#!/bin/bash

# dist is the distribution directory
aws s3 sync --delete dist s3://crunchypartoftheegg/dsny-baskets

DISTRIBUTION_ID=E3QT85KXOB88Q
echo "Invalidating cloudfront"
# Because this website is behind a cloudfront distribution, we need to
# invalidate the cloudfront cache everytime we deploy
INVALIDATION_ID=$(aws cloudfront create-invalidation \
  --distribution-id "$DISTRIBUTION_ID" \
  --paths "/dsny-baskets/*" \
  --output json | jq -r '.Invalidation.Id')

while true; do
  STATUS=$(aws cloudfront get-invalidation \
    --distribution-id "$DISTRIBUTION_ID" \
    --id "$INVALIDATION_ID" \
    --query 'Invalidation.Status' \
    --output text)

  echo "Invalidation status: $STATUS, sleeping for 5s"

  if [ "$STATUS" == "Completed" ]; then
    echo "Invalidation completed."
    break
  fi

  sleep 5
done

